Paul
desihub/desisurveyops pull request #1
Opened 2021-04-07 02:00 UTC by paulmartini

This repo seems like the right place to put my code to analyze and monitor observing efficiency.

2021-04-13 13:00 UTC, paulmartini commented
Hi @sbailey - I know you are swamped with other stuff. Perhaps you can find another person to do the review of this PR?

2021-04-13 23:08 UTC, sbailey requested changes
Thanks Paul.  I put some minor comments inline, plus a separate email comment.  More general comments:
* our desi standards is for bin/ script to _not_ have the `.py` extension, while things that are imported have the `.py` extension.
* In the context of this being installed with other desi code in the future, let's pick less generic script names than `plot_summary`, `plot_sequence`, `update_summary`, and `plot_night`, which could mean a lot of things and lead to confusion.
* similarly, several of the functions in `desisurveyops.utilities` seem specific to this use-case for survey ops, but not necessarily generically useful for other uses.  e.g. `get_twilights` is a nice generic utility function, while `calc_guidelists` seems pretty specific in what it does and what it outputs.  Consider moving some of them into a separate more focused submodule.
* Minor: Consider using `desisurveyops.utils` (like `desisurvey.utils` and `fiberassign.utils`) or `desisurveyops.util` (like `desispec.util`) rather than introducing a 3rd naming `desisurveyops.utilities`.

2021-04-14 03:15 UTC, paulmartini commented on py/desisurveyops/utilities.py
> +        outdir = '/global/cfs/cdirs/desi/users/martini/NightStats/'
Thanks for the general comments, Stephen. I've done the following:
- removed the .py on the bin/ scripts and gave them less generic names (plotnightobs, plotobsefficiency, plottimeobs, updateefficiency)
- moved more specific functions from utilities to obsdata.py 
- renamed utilities.py to utils.py to match the naming convention of other repos

I've also changed this specific case to report an error and raise an exception

2021-04-14 03:16 UTC, paulmartini commented on bin/plot_summary.py
> +    exit
Done

2021-04-14 03:21 UTC, paulmartini commented on py/desisurveyops/utilities.py
> +    datadir = '/global/cfs/cdirs/desi/spectro/data/'
I've switched to `$DESI_SPECTRO_DATA`, then try `$DESI_ROOT`,  and then raise an exception if this fails. I've also renamed the function `get_rawdatadir`.

2021-04-14 03:24 UTC, paulmartini commented on py/desisurveyops/utilities.py
> +    Set the root directory for the output and a NightlyData/ subdirectory
I've renamed this `get_outdir` and updated the docstring.

2021-04-14 03:25 UTC, paulmartini commented on py/desisurveyops/utilities.py
> +        os.mkdir(outdir)
Done

2021-04-14 03:26 UTC, paulmartini commented on py/desisurveyops/utilities.py
> +    desi.horizon = '-18'
Yes, I'd been meaning to do that and appreciate the nudge/reminder. Now takes the Sun altitude as an argument.

2021-04-14 03:30 UTC, paulmartini commented
Hi @sbailey - Thank you for the thorough review. I think I've addressed all of your comments. Would you please take another look when you have time? Thanks!

2021-04-15 22:12 UTC, sbailey approved these changes
Thanks for the updates.  Merging now.

2021-04-15 22:13 UTC, merged